### PR TITLE
Extract getting envs to app top level

### PR DESCRIPTION
**Pull request by aleklisi**
Pull request does not change existing functionality, but it allows to start goth on demand (with `Goth.Supervisor.start_link([{:json, json}])` and not when app starts.

### CODE REVIEW

**Comment by michalwski** [comment]
This change can be beneficial for many users of the lib. Can this be merged into master branch, @peburrows?

**Comment by peburrows** [comment]
Thanks, I'll review and get this merged soon.

**Comment by lccezinha** [comment]
@aleklisi @peburrows any changes about it?

**Comment by peburrows** [comment]
Sorry, I just kind of lost track of this PR. Taking a look now, though, it looks like tests are failing.

**Comment by lccezinha** [comment]
@peburrows seems a compilation error:

```
== Compilation error on file lib/goth/config.ex ==
** (CompileError) lib/goth/config.ex:54: undefined function config/0
    (stdlib) lists.erl:1337: :lists.foreach/2
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
```

**Comment by peburrows** [comment]
Yes, and that error isn't happening in master. It's related to this change, so that will need to be resolved first.

**Comment by peburrows** [comment]
Looks like there's still a failing test for this PR.

**Comment by rjacobskind** [comment]
I would love to see this PR merged in

**Comment by aleklisi** [comment]
I have fixing the PR on my TODO list, but have other stuff with a bit higher priority :(

**Comment by peburrows** [comment]
Thanks to @rjacobskind's work on #63, this has _finally_ been released (available in `v1.2.0`).

**Pull request closed without merging**
