### PR TITLE
return {:error, err} from Client.get_access_token/2 instead of crashing

### PR DESCRIPTION
**Pull request by peburrows**

### CODE REVIEW

**Comment by martin-cernak** [comment]
Will this be merged any time soon ?

**Comment by martin-cernak** [comment]
Thank you and congratulation :)

**Comment by peburrows** [comment]
After looking into merging this, it appears master has diverged significantly enough since I wrote this code that I'm going to have to go back and refactor / cleanup a lot of this implementation as it currently breaks a few things in master.

**Comment by peburrows** [comment]
Closing in favor of the refactored #47

**Pull request closed without merging**
