### PR TITLE
new env variable from spec

### PR DESCRIPTION
**Pull request by alexfilatov**
Added possibility to read JSON credentials from the ENV variable which points to JSON credentials file stored locally. This added flexibility for setting up different key files for different servers

### CODE REVIEW

**Comment by peburrows** [comment]
Hrm, we should definitely handle the case where the credentials path is in the `GOOGLE_APPLICATION_CREDENTIALS` ENV variable, but it seems a bit strange to treat `{:system, var}` differently depending on the name of the variable.

Let me investigate this a bit. This might very well be the best way to do it, but I want to think about whether or not there is a more elegant way to handle this situation.

**Comment by peburrows** [comment]
The solution might be to provide a `:json_path` config, as suggested in https://github.com/peburrows/goth/pull/15

**Comment by alexfilatov** [comment]
Yes, this is ok solution with :json_file, thanks for pointing me out.
What I mean in my Pull Request is a bit different: https://12factor.net/config - store all configuration in the environment, and per GC spec they suggest the same thing.
You are right - adding additional ENV_VAR looks not elegant at all, but I left it for backward compatibility.
DevOps guys will thank you for 12-factor solution :)

**Comment by dazuma** [comment]
Agreed that `:json_path` or similar would be good, to distinguish from the `:json` content.

And agreed that proper support for `GOOGLE_APPLICATION_CREDENTIALS`, and in general the entire [application default credentials](https://developers.google.com/identity/protocols/application-default-credentials) protocol, will be very important.

**Comment by dazuma** [comment]
This was superseded by https://github.com/peburrows/goth/pull/22. Suggest we close it.

**Comment by peburrows** [comment]
Agreed, closing.

**Pull request closed without merging**
